server:
  port: 9095
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: library
    password: library

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: none
=======
      ddl-auto: create
>>>>>>> 563f2705796f23ccf25b0bbcd00d241a9f34bd7f
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
<<<<<<< HEAD
        type: trace
=======
        type: trace
#        trace 는 모든 내용을 출력해준다
>>>>>>> 563f2705796f23ccf25b0bbcd00d241a9f34bd7f
